AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'Gemfile'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Exclude:
    - 'Gemfile'

Style/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb'

Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'bin/spring'
    - 'config/environments/production.rb'
    - 'config/puma.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
